# Copyright (C) 2024 CharlesWithC All rights reserved.
# Author: @CharlesWithC

import os

import argparse
import uvicorn

import api
from app import app

app.add_api_route(path="/banner", endpoint=api.get_banner, methods=["POST"])

drivershub = """    ____       _                         __  __      __
   / __ \\_____(_)   _____  __________   / / / /_  __/ /_
  / / / / ___/ / | / / _ \\/ ___/ ___/  / /_/ / / / / __ \\
 / /_/ / /  / /| |/ /  __/ /  (__  )  / __  / /_/ / /_/ /
/_____/_/  /_/ |___/\\___/_/  /____/  /_/ /_/\\__,_/_.___/
                                                         """

description = '''Start Drivers Hub Banner Generator.

NOTE: The generator may take a large amount of CPU and RAM. Set the number of workers cautiously.'''

parser = argparse.ArgumentParser(prog='main', description=description)
parser.add_argument("--host", help = "server host", default = "127.0.0.1")
parser.add_argument("--port", help = "server port", type=int, default = 8700)
parser.add_argument("--workers", help = "server workers", type=int, default = 2)
parser.add_argument("--enable-performance-header", help = "add headers telling the response time", action='store_true')
parser.add_argument("--memory-threshold", help = "limit memory consumption on low-end servers (in MB, default 0/disabled)", type=int, default=0)
args, _ = parser.parse_known_args() # unknown args generated by uvicorn

app.enable_performance_header = "enable_performance_header" in args.__dict__.keys() and args.enable_performance_header
app.memory_threshold = args.memory_threshold if "memory_threshold" in args.__dict__.keys() else 0

if __name__ == "__main__":
    from datetime import datetime
    currentDateTime = datetime.now()
    date = currentDateTime.date()
    year = date.strftime("%Y")
    print(drivershub)
    print("Drivers Hub: Backend | Banner Generator")
    print(f"Copyright (C) {year} CharlesWithC All rights reserved.")
    print("")

    if not os.path.exists("/tmp/hub"):
        os.mkdir("/tmp/hub")
    if not os.path.exists("/tmp/hub/banner"):
        os.mkdir("/tmp/hub/banner")
    if not os.path.exists("/tmp/hub/logo"):
        os.mkdir("/tmp/hub/logo")
    if not os.path.exists("/tmp/hub/template"):
        os.mkdir("/tmp/hub/template")
    if not os.path.exists("/tmp/hub/avatar"):
        os.mkdir("/tmp/hub/avatar")
    uvicorn.run("app:app", host=args.host, port=args.port, workers=args.workers, log_level="info", timeout_keep_alive=15)
