#!/usr/bin/python3

# Copyright (C) 2022-2026 CharlesWithC All rights reserved.
# Author: @CharlesWithC

import argparse
import base64
import json
import os

import uvicorn

import multilang as ml
import routing
from logger import logger

drivershub = """    ____       _                         __  __      __
   / __ \\_____(_)   _____  __________   / / / /_  __/ /_
  / / / / ___/ / | / / _ \\/ ___/ ___/  / /_/ / / / / __ \\
 / /_/ / /  / /| |/ /  __/ /  (__  )  / __  / /_/ / /_/ /
/_____/_/  /_/ |___/\\___/_/  /____/  /_/ /_/\\__,_/_.___/
                                                         """

description = '''Start Drivers Hub API Server.

Single or multiple Drivers Hub(s) may be started.
To start single Drivers Hub, use --config.
To start multiple Drivers Hubs within one server process, use --configs or --config-directory, and provide --parent-host, --parent-port, --parent-workers.

If --config is specified, --configs and --config-directory will not be considered. If --configs is specified, --config-directory will not be considered.'''

parser = argparse.ArgumentParser(prog='main', description=description)
parser.add_argument("--config", help = "path to single config file")
parser.add_argument("--configs", help = "path to multiple config files", nargs="*")
parser.add_argument("--config-directory", help = "path to a directory containing multiple config files")
parser.add_argument("--parent-host", help = "parent server host")
parser.add_argument("--parent-port", help = "parent server port", type=int)
parser.add_argument("--parent-workers", help = "parent server workers", type=int)
parser.add_argument("--banner-service-url", help = "url to banner service (default http://127.0.0.1:8700/banner)", default="http://127.0.0.1:8700/banner")
parser.add_argument("--use-master-db-pool", help = "use a single database connection pool rather than separate database connection pools for each hub", action='store_true')
parser.add_argument("--master-db-host", help = "master database host (required when --use-master-db-pool is enabled)")
parser.add_argument("--master-db-user", help = "master database user (required when --use-master-db-pool is enabled)")
parser.add_argument("--master-db-password", help = "master database password (required when --use-master-db-pool is enabled)")
parser.add_argument("--master-db-pool-size", help = "master database connection pool size (required when --use-master-db-pool is enabled)", type=int)
parser.add_argument("--enable-parent-openapi", help = "enable parent openapi", action='store_true')
parser.add_argument("--parent-openapi-path", help = "set parent openapi path (default /)")
parser.add_argument("--ignore-external-plugins", help = "ignore external plugins", action='store_true')
parser.add_argument("--rebuild-dlog-stats", help = "rebuild dlog stats table", action='store_true')
parser.add_argument("--enable-performance-header", help = "add headers telling the response time", action='store_true')
parser.add_argument("--disable-upgrader", help = "prevent running upgrader", action='store_true')
parser.add_argument("--force-upgrade-from", help = "force upgrade to upgrade from a version (2_x_x)")
parser.add_argument("--memory-threshold", help = "limit memory consumption on low-end servers (in MB, default 0/disabled)", type=int, default=0)
args, _ = parser.parse_known_args() # unknown args generated by uvicorn

config_paths = None
if args.config is not None:
    config_paths = [args.config]
elif args.configs is not None:
    config_paths = args.configs
elif args.config_directory is not None:
    if not os.path.exists(args.config_directory):
        logger.warning("Invalid config-directory, quited.")
        os._exit(42)
    config_files = sorted(os.listdir(args.config_directory))
    config_paths = [os.path.join(args.config_directory, x) for x in config_files if x.endswith(".json")]

openapi_path = ""
if args.enable_parent_openapi is True:
    if args.parent_openapi_path is not None:
        openapi_path = args.parent_openapi_path
        if not openapi_path.startswith("/"):
            openapi_path = "/" + openapi_path
    else:
        openapi_path = "/"

if config_paths is not None:
    os.environ["HUB_CONFIG"] = base64.b64encode(json.dumps(config_paths).encode()).decode()
    os.environ["OPENAPI_PATH"] = openapi_path
else:
    if 'HUB_CONFIG' not in os.environ.keys():
        logger.warning("No config is provided, quited.")
        os._exit(42)
    config_paths = json.loads(base64.b64decode(os.environ["HUB_CONFIG"].encode()).decode())
    openapi_path = os.environ["OPENAPI_PATH"]

if args.use_master_db_pool is True:
    if args.master_db_host is None or args.master_db_user is None or args.master_db_password is None or args.master_db_pool_size is None:
        logger.warning("Master database host, username, password and connection pool size must be provided when using master database pool, quited.")
        os._exit(42)
    if args.master_db_pool_size < 5:
        logger.warning("Master database connection pool size must be at least 5, quited.")
        os._exit(42)

if __name__ == "__main__":
    from app import version
    for line in drivershub.split("\n"):
        logger.info(line)
    logger.info(f"Drivers Hub: Backend (v{version})")
    logger.info("Copyright (C) 2022-2026 CharlesWithC All rights reserved.")
    logger.info(f"Languages: {', '.join(ml.LANGUAGES)}")
    logger.info("")

    scopes = routing.initRoutes(config_paths, openapi_path, first_init = True, args = args.__dict__)

scopes = routing.initRoutes(config_paths, openapi_path, args = args.__dict__)

if __name__ == "__main__":
    host = args.parent_host
    port = args.parent_port
    workers = args.parent_workers

    if host is None and port is None and scopes is None:
        logger.warning("--parent-host and --parent-port must be provided when starting multiple Drivers Hubs within one server process, quited.")
        os._exit(42)

    if scopes is not None:
        if host is None:
            host = scopes["host"]
        if port is None:
            port = scopes["port"]
        if workers is None:
            workers = scopes["workers"]

    uvicorn.run("routing:app", host=host, port=port, log_level="info", access_log=False, proxy_headers = True, workers = workers)
