#!/usr/bin/python3

# Copyright (C) 2023 CharlesWithC All rights reserved.
# Author: @CharlesWithC

import argparse
import os
import sys, base64, json
from datetime import datetime

import uvicorn

import multilang as ml
import routing

drivershub = """    ____       _                         __  __      __  
   / __ \_____(_)   _____  __________   / / / /_  __/ /_ 
  / / / / ___/ / | / / _ \/ ___/ ___/  / /_/ / / / / __ \\
 / /_/ / /  / /| |/ /  __/ /  (__  )  / __  / /_/ / /_/ /
/_____/_/  /_/ |___/\___/_/  /____/  /_/ /_/\__,_/_.___/ 
                                                         """

description = '''Create and start Drivers Hub API Server.

Single or multiple Drivers Hub(s) may be started.
To start single Drivers Hub, use --config.
To start multiple Drivers Hubs within one server process, use --configs or --config-directory, and provide --parent-host, --parent-port, --parent-workers.

If --config is specified, --configs and --config-directory will not be considered. If --configs is specified, --config-directory will not be considered.'''

parser = argparse.ArgumentParser(prog='main', description=description)
parser.add_argument("--config", help = "path to single config file")
parser.add_argument("--configs", help = "path to multiple config files", nargs="*")
parser.add_argument("--config-directory", help = "path to a directory containing multiple config files")
parser.add_argument("--parent-host", help = "parent server host")
parser.add_argument("--parent-port", help = "parent server port", type=int)
parser.add_argument("--parent-workers", help = "parent server workers", type=int)
args, _ = parser.parse_known_args() # unknown args generated by uvicorn

config_paths = None
if args.config is not None:
    config_paths = [args.config]
elif args.configs is not None:
    config_paths = args.configs
elif args.config_directory is not None:
    if not os.path.exists(args.config_directory):
        print("Invalid config-directory, aborted.")
        sys.argv(1)
    config_files = os.listdir(args.config_directory)
    config_paths = [os.path.join(args.config_directory, x) for x in config_files]
else:
    print("No config is provided, aborted.")

if config_paths is not None:
    os.environ["HUB_CONFIG"] = base64.b64encode(json.dumps(config_paths).encode()).decode()
else:
    config_paths = json.loads(base64.b64decode(os.environ["HUB_CONFIG"].encode()).decode())

if __name__ == "__main__":
    from app import version
    currentDateTime = datetime.now()
    date = currentDateTime.date()
    year = date.strftime("%Y")
    print(drivershub)
    print(f"Drivers Hub: Backend (v{version})")
    print(f"Copyright (C) {year} CharlesWithC All rights reserved.")
    print(f"Languages: {', '.join(ml.LANGUAGES)}")
    print("")

    scopes = routing.initRoutes(config_paths, first_init = True)

scopes = routing.initRoutes(config_paths)

if __name__ == "__main__":
    if scopes is not None:
        uvicorn.run("routing:app", host=scopes["host"], port=scopes["port"], log_level="info", access_log=False, proxy_headers = True, workers = scopes["workers"])
    else:
        if args.parent_host is None or args.parent_port is None:
            print("--parent-host and --parent-port must be provided when starting multiple Drivers Hubs within one server process.")
            sys.exit(1)
        workers = 1 if args.parent_workers is None else args.parent_workers
        uvicorn.run("routing:app", host=args.parent_host, port=args.parent_port, log_level="info", access_log=False, proxy_headers = True, workers = workers)